const vocab={
  "superfluous":" unnecessary; extra",
  "litany": "a prayer or chant; a long list",
  "peculate": "to steal another's money or property",
  "diminutive": "smaller than average",
  "caprice": "a sudden unpredictable or whimsical change",
  "ameliorate": "to improve or make better",
  "tedious": "boring, repetitive and tiresome",
  "couture": "fashion design; fashionable clothing",
  "burgeon": "to grow or develop quickly",
  "caustic": "harsh or corrosive",
  "peregrination": "the act of traveling; an excursion",
  "heed": "to pay close attention to",
  "destitute": "poor, living in poverty",
  "anecdote": "a short personal account of an event",
  "vindicate": "to show to be right",
  "bestial": "showing a lack of human sensibility; like an animal",
  "quandary": "a state of perplexity; a difficult situation",
  "recant": "to withdraw a previously held statement of belief",
  "incredulous": "skeptical",
  "heresy": "a belief that rejects the accepted tenets of a religion",
  "deprecate": "to express disapproval of",
  "cerebral": "relating to the brain; intellectual",
  "acrimony": "sharpness or bitterness in language or manner",
  "synthesize": "to combine various components into a new whole",
  "sedentary": "characterized by sitting",
  "husbandry": "management of resources, especially in agriculture",
  "incarcerate": "to put somebody in prison",
  "stolid": "unemotional, not easily excited",
  "censure": "an expression of disapproval; to criticize or disapprove of",
  "placate": "to make somebody less angry",
  "inveterate": "firmly established in a habit",
  "cloister": "a tranquil and secluded place",
  "refurbish": "to restore something to a better condition",
  "nebulous": "unclear or vague",
  "derision": "the act of mocking; ridicule, mockery",
  "vilify": "to spread negative information about",
  "affable": "friendly, good-natured",
  "archaism": "an old expression or practice that is no longer used",
  "plumb": "to measure the depth of something",
  "derogatory": "belittling; uncomplimentary",
  "deference": "courtesy, respect; submission to another person's opinion or wishes",
  "mandate": "to order something officially",
  "sinuous": "full of curves; twisting and turning",
  "paucity": "scarcity",
  "commiserate": "to show sympathy for",
  "clandestine": "done secretly",
  "accolade": "a sign of approval or respect",
  "comport": "to behave well or properly",
  "determinate": "having distinct limits",
  "accomplice": "a partner; a partner-in-crime",
  "condescend": "to treat others as socially or intellectually inferior",
  "fallacious": "misleading; based on incorrect information",
  "legerdemain": "a display of cleverness, especially to deceive others",
  "vex": "to annoy",
  "overweening": "arrogant; excessive",
  "potentate": "a powerful ruler; an important person",
  "impede": "to be a hindrance or obstacle to",
  "stagnant": "motionless, uncirculating",
  "carping": "petty nagging criticism",
  "entreat": "to ask earnestly",
  "impetuous": "characterized by excessive haste and lack of deliberation; moving with great force and energy",
  "sacrilege": "improper or disrespectful treatment of something sacred",
  "sanction": "to give authority or permission",
  "eccentric": "unconventional or unusual",
  "idiosyncrasy": "any personal peculiarity, mannerism",
  "cavort": "to frolic",
  "sylvan": "pertaining to or characteristic of a forest or woodland",
  "tableau": "a picturesque display",
  "confound": "to lump together, causing confusion; to damn",
  "insidious": "slowly and subtly harmful",
  "iconoclast": "somebody who challenges established beliefs, customs, and values",
  "obviate": "to do away with or make unnecessary; to prevent",
  "laconic": "using few words",
  "loquacity": "the quality of being wordy and talkative",
  "abdicate": "to give up a duty or a position",
  "onerous": "burdensome; oppressive",
  "coterie": "a group of people with a common interest",
  "disseminate": "to distribute or spread something, especially information",
  "apocryphal": "of questionable authenticity",
  "cacophony": "an unpleasant noise",
  "conjure": "to summon; to bring into being as if by magic",
  "ingenuous": "innocent, naive; honest",
  "opprobrium": "a state of shame or disgrace; scorn, contempt",
  "inculcate": "to teach by frequent repetition",
  "winsome": "charming",
  "penchant": "a strong liking",
  "abscond": "to leave secretly",
  "ephemeral": "lasting a short time",
  "pariah": "one who is rejected by a social group",
  "consummate": "to bring to a state of completion or perfection; complete or perfect",
  "garrulous": "talking too much; wordy",
  "duress": "imprisonment; the use of threats",
  "forbear": "to not do something",
  "inchoate": "just beginning to develop; lacking structure or organization",
  "gamin": "a child who roams the streets",
  "subjugate": "to bring somebody under the control of another",
  "immaculate": "perfectly clean, pure; without faults",
  "charlatan": "one who feigns knowledge or ability; an imposter",
  "occlude": "to stop up; to cut off the flow",
  "prodigal": "extravagantly wasteful",
  "foible": "a minor flaw or failing",
  "obfuscate": "to make unclear",
  "perfunctory": "done hastily and without attention to detail; indifferent",
  "debutante": "a young woman being introduced to society",
  "attenuate": "to make thin or slender; to weaken or lessen in intensity",
  "perfidious": "intending to betray",
  "remuneration": "a payment; the act of paying",
  "inure": "to cause to accept or become hardened to, to habituate",
  "choleric": "easily angered, irascible",
  "cynic": "one who distrusts human nature",
  "corroborate": "to support with evidence or authority",
  "emollient": "soothing; a soothing substance",
  "progeny": "descendants, offspring; followers",
  "burnish": "to polish by rubbing",
  "pedantic": "overly concerned with formal rules and details",
  "inception": "the beginning of something",
  "pervade": "to spread throughout",
  "fatuous": "stupid or foolish in a self-satisfied way",
  "blandishment": "anything designed to flatter or coax",
  "fleece": "to defraud or swindle",
  "acrid": "sharp; bitter; foul smelling",
  "neologism": "a newly invented word or phrase",
  "expostulate": "to attempt to dissuade somebody from doing something",
  "insipid": "dull; lacking flavor",
  "aberration": "something different from the usual or normal",
  "rebuff": "to snub, drive away, reject",
  "decorous": "characterized by proper manners and conduct",
  "sepulchre": "a burial chamber",
  "desiccate": "to dry out",
  "pellucid": "transparent; clear in meaning",
  "martinet": "somebody who demands exact conformity to rules",
  "ossify": "to harden into bone",
  "obsequious": "attempting to win favor by flattery and submissiveness, fawning",
  "torpor": "a lack of energy or vigor, lethargy",
  "flaunt": "to display proudly",
  "authoritarian": "demanding obedience; a dictator",
  "platitude": "a trite statement",
  "impugn": "to criticize or cast doubt on",
  "exigent": "critical, requiring immediate action",
  "affectation": "unnatural behavior intended to impress",
  "polarize": "to cause a division of opinion between groups",
  "estimable": "deserving of respect",
  "elegy": "a sorrowful poem or speech",
  "brook": "to tolerate something or somebody unpleasant",
  "dauntless": "fearless; not discouraged",
  "dilettante": "an amateur",
  "dissemble": "to pretend; to hide under a false appearance",
  "imminent": "about to happen",
  "aperture": "an opening, gap, hole",
  "espouse": "to support or adopt",
  "pertinacious": "holding firmly to a course of action or a set of beliefs",
  "progenitor": "an ancestor in the direct line",
  "ingratiate": "to seek to please somebody to gain favor",
  "captious": "overly critical and complaining",
  "veracity": "truthfulness",
  "descant": "to talk or write at length",
  "ineffable": "impossible to describe in words",
  "paroxysm": "a sudden uncontrollable spasm",
  "beget": "to make children; to cause",
  "credulous": "too trusting; gullible",
  "mainstay": "somebody or something that plays an important role",
  "venerate": "to respect and honor",
  "ostensible": "represented or appearing in one way, but not necessarily that way in reality",
  "promiscuity": "the practice of indulging in casual sexual relations",
  "improvise": "to perform without preparation",
  "deleterious": "harmful; hurtful; noxious",
  "sycophant": "a person who serves and flatters someone powerful for personal gain",
  "flout": "to treat with contemptuous disregard",
  "mercurial": "tending to change mood or behavior suddenly and unpredictably",
  "epigram": "a witty saying",
  "expedite": "to speed up the progress of",
  "saturnine": "melancholy, gloomy, morose",
  "distaff": "work or other matters regarded as the concern of women",
  "temporize": "to stall or act evasively in order to gain time",
  "esoteric": "known or understood by only a few",
  "celerity": "swiftness",
  "reconnoiter": "to explore an area and gather information, especially about enemy forces",
  "taciturn": "reserved and generally quiet",
  "consanguinity": "a relationship by blood",
  "goad": "to urge; to give courage to",
  "sedulous": "working diligently and carefully",
  "largesse": "generosity in giving",
  "augur": "to indicate by signs; to predict from an omen",
  "hermetic": "sealed tightly; protected from outside influence",
  "suppliant": "one who makes a request humbly and earnestly; asking humbly and earnestly",
  "immure": "to imprison, to incarcerate",
  "sublime": "beautiful, heavenly, inspiring awe",
  "acumen": "mental sharpness",
  "expropriate": "to take arbitrarily or by force",
  "effervescent": "bubbling, excited",
  "guile": "the use of tricks to deceive someone",
  "repine": "to express discontent",
  "dilatory": "intended to delay",
  "encumbrance": "a burden",
  "enervate": "to weaken",
  "gregarious": "outgoing, sociable",
  "panegyric": "a formal expression of praise",
  "denigrate": "to defame, to blacken or sully; to belittle",
  "verdant": "green with vegetation; green; inexperienced",
  "antipathy": "intense hatred",
  "exonerate": "to pronounce not guilty",
  "tortuous": "highly intricate; winding",
  "recidivism": "the act of returning to a life of crime",
  "abnegate": "to renounce something",
  "restive": "hard to manage",
  "compunction": "feelings of shame and regret",
  "eschew": "to avoid, shun, keep away from",
  "aesthetic": "of beauty; pertaining to taste in art and beauty",
  "scion": "a young descendant or heir",
  "oscillate": "to move from side to side regularly",
  "turgid": "bombastic; swollen",
  "abeyance": "suspension of activity",
  "prevaricate": "to be intentionally ambiguous or unclear in order to mislead",
  "salacious": "characterized by lust",
  "harbinger": "something that foreshadows a future event",
  "reciprocate": "to give back in return",
  "diffident": "lacking self-confidence",
  "reticence": "the trait of being uncommunicative",
  "promulgate": "to proclaim or issue officially",
  "brusque": "abrupt or curt in manner or speech",
  "propinquity": "the property of being close together",
  "excoriate": "to criticize severely",
  "artful": "not straightforward or candid; crafty",
  "insolence": "disrespect, rudeness",
  "disabuse": "to free from error",
  "soporific": "causing sleep or lethargy",
  "kismet": "fate or destiny",
  "accrete": "to grow together",
  "unwonted": "not usual or expected; not in character",
  "nostrum": "a hypothetical cure-all that may have no true efficacy",
  "abrogate": "to formally revoke an agreement or contract",
  "perspicacious": "keen in observation and understanding",
  "perquisite": "a privilege that goes along with a job",
  "demur": "to object; an objection",
  "moribund": "dying, on the way out",
  "dudgeon": "a fit of anger",
  "lionize": "to treat as a celebrity",
  "histrionic": "pertaining to actors and their techniques; theatrical, artificial, melodramatic",
  "anachronism": "something from a different historical period of time",
  "palliate": "to treat the symptoms",
  "indolent": "lazy",
  "coda": "the closing section of a musical composition",
  "importune": "to trouble with demands; to beg for insistently",
  "impudent": "showing casual disrespect",
  "effigy": "a crude image of a despised person",
  "proscribe": "to outlaw",
  "torpid": "sluggish, lacking energy",
  "welter": "a confused multitude of things",
  "imprecate": "to pray for evil; to invoke a curse",
  "furtive": "done secretly",
  "countenance": "facial expression; composure; to tolerate or support",
  "emulate": "to try to equal somebody or something",
  "indigent": "needy, impoverished",
  "raillery": "friendly teasing",
  "winnow": "to sift through removing what is unwanted and keeping what is desirable",
  "hapless": "having persistent bad luck",
  "peripatetic": "a worker who travels around; traveling, especially for work",
  "perjure": "to tell a lie in a court of law",
  "adventitious": "associated with something by chance and not an integral part",
  "raconteur": "a skilled story-teller",
  "descry": "to catch sight of",
  "bucolic": "of the countryside or country life",
  "zenith": "the highest point",
  "sequester": "to separate or segregate",
  "officious": "annoyingly eager to help",
  "gaucherie": "social awkwardness",
  "forfend": "to prevent something from happening",
  "wizened": "dry, shrunken, and wrinkled",
  "raiment": "clothing, garments",
  "hector": "to bully",
  "chary": "extremely cautious or hesitant",
  "effluent": "liquid waste; a stream",
  "cower": "to huddle and tremble",
  "penitent": "regretful for one's sins; one who is sorry for wrongdoing",
  "cabal": "a group of people with secret purposes and meetings",
  "cloy": "to sicken somebody with too much of a good thing",
  "profligate": "recklessly wasteful; having low morals",
  "riposte": "a quick and witty reply",
  "pillory": "to punish in public; a device for public punishment",
  "refulgent": "shining, radiant",
  "hedonist": "a person who lives for pleasure",
  "defenestrate": "to throw out of a window",
  "felicitous": "appropriate; happy",
  "petulance": "the quality of being easily irritated",
  "malinger": "to pretend to be ill in order to avoid a responsibility",
  "fastidious": "demanding, concerned with every detail",
  "fealty": "allegiance or loyalty",
  "patronize": "to do business with; to treat somebody as unintelligent",
  "macabre": "gruesome; distressing",
  "contusion": "a bruise; an injury where the skin is not broken",
  "indemnify": "to insure against or pay for loss or damage",
  "itinerant": "moving around to find work; a person who travels from place to place",
  "gambit": "a maneuver in a game or conversation used to secure an advantage",
  "proselytize": "to try to convert somebody",
  "plenary": "attended by all members; complete in all aspects",
  "zephyr": "a slight breeze",
  "bereave": "to deprive through death",
  "quotidian": "ordinary, mundane",
  "rampart": "a fortification",
  "simper": "to smile artificially",
  "trenchant": "sharp, incisive; forceful, effective",
  "nadir": "the lowest point",
  "vitiate": "to make something ineffective; to degrade",
  "pusillanimous": "contemptibly cowardly",
  "canard": "a false rumor",
  "enfranchise": "to grant privileges of citizenship, especially the right to vote",
  "rebarbative": "serving or tending to repel",
  "cynosure": "the center of attraction; something that serves to guide or direct",
  "bowdlerize": "to modify by removing inappropriate sections from a text",
  "incendiary": "intending or designed to start fires; tending to stir up strife; one who sets fires or causes strife",
  "mendacity": "the tendency to be untruthful",
  "galvanize": "to stimulate as if by electric shock; to excite",
  "diurnal": "active during the daytime",
  "detritus": "debris or discarded material",
  "propitiate": "to win somebody's favor",
  "specious": "plausible but false",
  "apotheosis": "a paragon; elevation to divine status",
  "extrapolate": "to guess at general conclusions based on what is already known",
  "desultory": "passing aimlessly from one thing to another; random",
  "apothegm": "a short instructive saying",
  "capitulate": "to surrender; to give up or give in",
  "halcyon": "calm, peaceful; prosperous",
  "pedant": "somebody too concerned with rules and details",
  "efface": "to remove; to be inconspicuous",
  "jejune": "lacking in nutritive value; uninteresting; juvenile",
  "ostentation": "conspicuous display intended to impress others",
  "philander": "to have amorous affairs",
  "bourgeois": "conforming to standards and conventions of the middle class",
  "magnate": "a powerful business-person",
  "distend": "to swell up",
  "ersatz": "artificial and inferior",
  "expurgation": "the removal of indecent passages from a text",
  "convalesce": "to recover from an illness",
  "recumbent": "lying down",
  "fracas": "a noisy quarrel",
  "decamp": "to leave suddenly or secretly",
  "prodigious": "enormous; exceptional",
  "mettle": "strength of character, determination",
  "litigate": "to engage in legal proceedings",
  "sententious": "overly moralizing",
  "homily": "a sermon",
  "expatriate": "to expel from a country; to move away from one's home country; one who has left his country",
  "meretricious": "attractive in a superficial manner but without real value",
  "shibboleth": "a slogan",
  "discomfit": "to cause to lose one's composure",
  "esurient": "very hungry or greedy",
  "effrontery": "an arrogant attitude or behavior that is insulting to others",
  "adulate": "to praise too greatly",
  "redolent": "suggestive or reminiscent of something; having an aroma",
  "sophistry": "a flawed argument",
  "engender": "to create; to arise or come into existence",
  "plaintive": "expressive of sorrow or woe",
  "luminary": "an important or famous person",
  "rarefy": "to make something less dense; to refine",
  "abstruse": "difficult to understand",
  "perfidy": "betrayal or deceit",
  "garner": "to gather or gain something",
  "anterior": "near the front or head of the body",
  "sopor": "a deep sleep",
  "remonstrate": "to argue strongly against some action",
  "prurient": "characterized by lust",
  "badinage": "light and playful conversation",
  "arrogate": "to claim or take without right",
  "peremptory": "dictatorial",
  "fustian": "pompous or pretentious speech, bombast",
  "cajole": "to coax with insincere talk",
  "inexorable": "impossible to stop",
  "proclivity": "a natural inclination",
  "apotheosize": "to glorify; to make into a god",
  "moot": "open to argument; irrelevant",
  "proletariat": "the working class",
  "slough": "to discard; to ignore; a swamp",
  "truculent": "aggressively defiant or hostile",
  "rapprochement": "reconciliation",
  "gainsay": "to oppose; to claim that something is false",
  "declamatory": "lofty in style, bombastic",
  "philistine": "someone who is uncultured and indifferent to intellectual matters",
  "discourse": "to communicate in an orderly fashion",
  "turbid": "muddy; cloudy",
  "neophyte": "a beginner",
  "condone": "to excuse or make allowances for",
  "venal": "capable of being bribed; corrupt",
  "philippic": "a violent verbal attack",
  "undermine": "to weaken gradually; to discredit",
  "bromidic": "dull, unoriginal",
  "alacrity": "liveliness and eagerness",
  "forsake": "to withdraw support",
  "apocalyptic": "predicting or involving widespread destruction",
  "toady": "a person who tries to please others to gain a personal advantage",
  "fulminate": "to criticize severely",
  "urbane": "sophisticated and refined",
  "encomium": "a formal expression of praise, a eulogy",
  "requite": "to pay something back for a service or a kindness",
  "fecund": "fruitful in offspring or vegetation; intellectually productive",
  "threnody": "a speech of lament for the dead",
  "equivocate": "to be deliberately unclear or ambiguous",
  "picayune": "having little value or importance",
  "mercenary": "a hired soldier; someone motivated only by money",
  "assuage": "to relieve; ease; make less severe",
  "maudlin": "silly and overly sentimental",
  "mendicant": "a beggar",
  "nullify": "to declare invalid",
  "seraphic": "like an angel",
  "discernment": "an ability to make good judgments",
  "cavil": "to raise trivial objections; to bicker",
  "judicious": "having wisdom or discretion",
  "anomaly": "something that is unusual or unexpected",
  "calumniate": "to slander",
  "phlegmatic": "showing little emotion",
  "travesty": "a distorted representation of something",
  "extemporize": "to perform without preparation",
  "monolithic": "massive and uniform",
  "animus": "a feeling of hostility; motivation",
  "exculpate": "to clear from blame",
  "tantamount": "equivalent to",
  "patrician": "a member of the aristocracy",
  "vacillate": "to be undecided; to sway back and forth",
  "sanguine": "cheerful and optimistic",
  "peccadillo": "a minor offense",
  "presage": "to foretell something"
};

    const list = document.getElementById('vocab-list');
    for (const word in vocab) {
      if (vocab.hasOwnProperty(word)) {
        const li = document.createElement('li');
        li.innerHTML = `<span class="word">${word}</span>: ${vocab[word]}`;
        list.appendChild(li);
      }
